[package]
name = "commitment"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
colored = "2.0.4"
git2 = "0.17.2"
lazy_static = "1.4.0"
log = "0.4.20"
regex = "1.10.2"
ucfirst = "0.1.0"
