[package]
name = "commitment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.3"
git2 = "0.17.2"
regex = "1.8.4"
ucfirst = "0.1.0"
